server.contextPath: /auth
spring:
    datasource:
        password: redhat
        tomcat:
            max-active: 50
            max-idle: 20
            max-wait: 20000
            min-idle: 15
        url: jdbc:mysql://localhost:3306/oauthdb
        username: root
    jpa:
        hibernate:
          ddl-auto: update
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
                id:
                    new_generator_mappings: false
logging:
 level:
   org.springframework.security: DEBUG
server:
 port: 8080
keystore:
  password: mySecretKey